name: Windows MSVC x64

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: ${{ matrix.build }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build: [ debug, release ]

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset default

      - name: Build
        run: cmake --build --preset ${{ matrix.build }}
