name: Windows MSVC x86

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: ${{ matrix.build }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build: [ x86-debug, x86-release ]

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset msvc-x86

      - name: Build
        run: cmake --build --preset ${{ matrix.build }}
